name: Create GitHub Release

on:
  workflow_dispatch:
    branches:
      - default

jobs:
  create-release:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Ensure Wally+NPM Version Numbers Match
        run: |
          NPM_VERSION=$( jq -r '.version' package.json )
          WALLY_VERSION=$( grep -Po '(?<=version = ")([^"]+)' wally.toml )

          if [ -z "$NPM_VERSION" ]; then
            echo "NPM version not found in package.json"
            exit 1
          fi

          if [ -z "$WALLY_VERSION" ]; then
            echo "Wally version not found in wally.toml"
            exit 1
          fi

          if [ "$WALLY_VERSION" != "$NPM_VERSION" ]; then
            echo "Wally version ($WALLY_VERSION) does not match NPM version ($NPM_VERSION)"
            exit 1
          fi

      - name: Setup Toolchain
        uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: "^1.0.1"

      - name: Report Tool Versions
        run: foreman list

      - name: Get Release Details
        shell: bash
        run: echo "PROJECT_VERSION=`grep -Po '(?<=version = ")([^"]+)' wally.toml`" >> $GITHUB_ENV

      - name: Set Release Filename
        shell: bash
        run: |
          echo "RELEASE_FILENAME=${{ github.event.repository.name }}-$PROJECT_VERSION.rbxm" >> $GITHUB_ENV

      - name: Install Dependencies
        run: wally install

      - name: Remove Tests
        run: |
          find . -name "*.spec.lua" -delete

      - name: Build Project
        run: rojo build default.project.json -o $RELEASE_FILENAME

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.PROJECT_VERSION }}
          tag_name: ${{ env.PROJECT_VERSION }}
          fail_on_unmatched_files: true
          files: |
            ${{ env.RELEASE_FILENAME }}
          draft: true
